# Generated by Django 5.0.7 on 2024-07-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_item_alter_conversation_item'),
        ('item', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='item.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
